[package]
name = "cpi_virtualbox"
version = "0.1.3"
edition = "2024"

[lib]
name = "cpi_virtualbox"
crate-type = ["cdylib"]

[dependencies]
lib_cpi = { version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"