[package]
name = "virtualbox_extension"
version = "0.1.0"
edition = "2024"

[lib]
name = "virtualbox_extension"
crate-type = ["cdylib"]

[dependencies]
lib_cpi = { version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"